# Generated by Django 5.2.15 on 2026-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_event_online_type_event_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('economy', '경제'), ('invest', '투자'), ('saving', '저축'), ('finance', '금융상품'), ('society', '사회'), ('etc', '기타')], default='economy', max_length=20, verbose_name='카테고리'),
        ),
    ]
