# Generated by Django 5.2.15 on 2026-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='유튜브 영상 ID'),
        ),
    ]
