# Generated by Django 5.2.15 on 2026-06-25 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_event_address_event_latitude_event_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='scraps',
            field=models.ManyToManyField(blank=True, related_name='scrapped_contents', to=settings.AUTH_USER_MODEL, verbose_name='스크랩'),
        ),
        migrations.AddField(
            model_name='event',
            name='scraps',
            field=models.ManyToManyField(blank=True, related_name='scrapped_events', to=settings.AUTH_USER_MODEL, verbose_name='스크랩'),
        ),
    ]
