# Generated by Django 5.2.15 on 2026-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('economy', '경제'), ('management', '경영'), ('finance', '금융'), ('society', '사회'), ('science', '과학'), ('etc', '기타')], default='economy', max_length=20, verbose_name='주제')),
                ('term', models.CharField(max_length=120, verbose_name='용어')),
                ('description', models.TextField(verbose_name='설명')),
                ('initial', models.CharField(blank=True, db_index=True, max_length=4, verbose_name='두문자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
    ]
