# Generated by Django 5.2.15 on 2026-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='요약')),
                ('body', models.TextField(blank=True, verbose_name='본문')),
                ('category', models.CharField(choices=[('economy', '경제'), ('invest', '투자'), ('saving', '저축'), ('finance', '금융상품'), ('etc', '기타')], default='economy', max_length=20, verbose_name='카테고리')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='contents/', verbose_name='썸네일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='추천 콘텐츠')),
                ('is_popular', models.BooleanField(default=False, verbose_name='인기 콘텐츠')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='요약')),
                ('body', models.TextField(blank=True, verbose_name='본문')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='썸네일')),
                ('status', models.CharField(choices=[('open', '모집중'), ('closed', '모집마감'), ('ended', '종료')], default='open', max_length=10, verbose_name='상태')),
                ('host', models.CharField(blank=True, max_length=100, verbose_name='주최')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
