# Generated by Django 5.2.15 on 2026-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_likes_contentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_type',
            field=models.CharField(choices=[('offline', '오프라인'), ('online', '온라인'), ('both', '온·오프라인')], default='offline', max_length=10, verbose_name='진행 방식'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=30, verbose_name='지역'),
        ),
    ]
