# Generated by Django 5.2.15 on 2026-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_content_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='장소명'),
        ),
    ]
