# Generated by Django 5.2.15 on 2026-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_content_scraps_event_scraps'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='외부 링크'),
        ),
    ]
