# Generated by Django 5.2.15 on 2026-06-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=30, verbose_name='지역'),
        ),
    ]
