# Generated by Django 5.2.15 on 2026-06-24 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='출제일')),
                ('question', models.CharField(max_length=300, verbose_name='문제')),
                ('options', models.JSONField(verbose_name='보기')),
                ('answer_index', models.PositiveSmallIntegerField(verbose_name='정답 번호')),
                ('explanation', models.CharField(blank=True, max_length=500, verbose_name='해설')),
                ('source', models.CharField(default='ai', max_length=10, verbose_name='생성 출처')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '오늘의 퀴즈',
                'verbose_name_plural': '오늘의 퀴즈',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='출석일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField(verbose_name='선택 번호')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='응답일시')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.dailyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
