# Generated by Django 5.2.15 on 2026-06-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_likes_comment_parent_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('free', '자유게시판'), ('review', '후기게시판'), ('info', '정보게시판'), ('qna', '질문게시판'), ('study', '스터디 모집')], default='free', max_length=10, verbose_name='게시판'),
        ),
    ]
