# Generated by Django 5.2.15 on 2026-06-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('notice', '공지'), ('free', '자유 게시판'), ('review', '후기 게시판'), ('info', '정보 게시판'), ('qna', '질문 게시판'), ('study', '스터디 모집')], default='free', max_length=10, verbose_name='게시판'),
        ),
    ]
